### PR TITLE
Updated file names that break on git checkout

### PR DESCRIPTION
**Pull request by cmstead**
As soon as I checked out the fork, these files broke on my Windows machine. I renamed them so they won't break for others. I hope this is alright.

### CODE REVIEW

**Comment by JayBazuzi** [comment]
Read #7 and then tell me you still think the renames are important.

**Comment by cmstead** [comment]
I understand the hesitancy to rename, but I actually have a number of snippets for markdown I use regularly. I rely on the markdown preview in VS Code, as well, so I can verify that I didn't break anything.  (Example: I created a link, but I didn't realize it had to be hand-url-encoded, so it was broken)

Also, I really don't like editing source inline on GitHub. I want to divest my editing from the source control interface, plus I really don't enjoy working in their editor.

I'm open to another alternative, I just want to ensure that I (and anyone else like me) can safely clone, edit, and interact with the repo in a stable way, locally.

**Comment by cmstead** [comment]
One other bit of sad: updating forks inside of GitHub is non-obvious. You have to create a backwards pull into your fork, which means it's going to be hard for people who aren't GH power users to keep their fork up to date as a web-only interface. The update from upstream in the command line is (a little) more sensible and straightforward, but it doesn't work on Windows machines ATM.

If you want me to throw all of this into the issue, I can do that, which will facilitate more conversation.  For the moment, I will just hand-PR the couple of files and changes I made.

**Comment by JayBazuzi** [comment]
It looks like we'll get a fix for this after all: https://github.com/alexanderbird/Mobbing-Pattern-Language/commit/e6076992c5d959d9cdeb800d0ad7c3329f9ddbaf

**Pull request closed without merging**
