### PR TITLE
Experimental Jekyll/Github Pages implementation with tags

### PR DESCRIPTION
**Pull request by alexanderbird**
Re Issue #1 

Live demo: https://alexanderbird.github.io/Mobbing-Pattern-Language/

Still to do:
- Mobile view
- Make it pretty
- link to the Github Pages url from the Github repo
- tag more pages (I just put a few on there for the demo, didn't put much thought into it)

Feb-08-2020 14-32-37

### CODE REVIEW

**Comment by alexanderbird** [comment]
Is this interesting for people? No hard feelings if you don't think it's a useful direction to go -- I learned something in the process so I've got what I wanted out of it.

**Comment by alexanderbird** [comment]
Screen Shot 2020-02-08 at 2 54 45 PM

Screen Shot 2020-02-08 at 2 56 38 PM

@JayBazuzi is handling the punctuation this way ok?

**Comment by JayBazuzi** [comment]
I think this is awesome, and right in line with some things that @cmstead has talked about.

**Comment by alexanderbird** [comment]
I've hacked together a mobile view that collapses the navigation. 

mobile-view

I've been on vacation this past week but am back to work on Monday so I likely won't be able to work on this much more in the near future. Are there any big items keeping you from merging this, I might be able to do a little more?

**Comment by JayBazuzi** [comment]
If you think it's ready, I'll merge it any time.

**Comment by cmstead** [comment]
This is awesome!

**Comment by alexanderbird** [comment]
> If you think it's ready, I'll merge it any time.

Yeah, the only big thing I see is tagging the rest of the patterns -- probably if we don't do it now that we're thinking of it it'll go undone for a while. Do you or @cmstead have any time to put some more tags on patterns? 

I'll also open an issue for general styling of the site, it may be that someone who finds the content useful wants to dedicate some time to sprucing it up -- having an issue ready to go would help with that. But I think the brutalist look is fine for now -- better than nothing.

**Comment by cmstead** [comment]
I'm glad to throw some effort in. You did a lot of heavy lifting. Thanks for doing all this work!

**Comment by alexanderbird** [comment]
> I'm glad to throw some effort in. You did a lot of heavy lifting. Thanks for doing all this work!

Excellent! And I was happy to :)

**Pull request merged**
